name: ranking
description: A library to compute rankings of players.

version: 0.1.0
author: Florian Loitsch <florian@loitsch.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
