name: ranking
description:
  A library to compute rankings of players.
  Uses ELO for dynamic rankings, and Bradley-Terry for static rankings.

version: 1.0.1
homepage: https://github.com/floitsch/ranking

environment:
  sdk: '>=2.2.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
