name: ranking
description: A library to compute rankings, such as the ELO rating.
version: 0.0.1
# homepage: https://www.example.com
author: Florian Loitsch <florian@loitsch.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
